# Generated by Django 6.0.3 on 2026-04-23 08:56

import AC_Library.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('school_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('book_copies_available', models.IntegerField(default=1)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AC_Library.category')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('overdue_date', models.DateField(default=AC_Library.models.calculate_overdue_date)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC_Library.book')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC_Library.student')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_date', models.DateField(default=datetime.datetime.today)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC_Library.issue')),
            ],
        ),
    ]
