# Generated by Django 6.0.3 on 2026-04-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category_id',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='category_id',
            new_name='genre_id',
        ),
    ]
