# Generated by Django 6.0.3 on 2026-04-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0002_rename_category_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
