# Generated by Django 6.0.3 on 2026-04-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0002_category_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='genre_name',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
