# Generated by Django 6.0.3 on 2026-04-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0002_return_overdue_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='overdue_fine',
        ),
    ]
