# Generated by Django 6.0.3 on 2026-04-30 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0003_book_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AC_Library.book'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AC_Library.student'),
        ),
        migrations.AlterField(
            model_name='return',
            name='issue_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AC_Library.issue'),
        ),
    ]
