# Generated by Django 6.0.3 on 2026-04-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0003_rename_category_book_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='book_author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='book_genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_title',
        ),
    ]
