# Generated by Django 6.0.3 on 2026-04-20 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0004_rename_author_book_book_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('borrow_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('borrowed_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC_Library.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC_Library.student')),
            ],
        ),
    ]
