# Generated by Django 6.0.3 on 2026-07-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0005_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
