# Generated by Django 6.0.3 on 2026-04-20 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0005_borrowrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('overdue_date', models.DateField(blank=True, null=True)),
                ('issued_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC_Library.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC_Library.student')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_date', models.DateField()),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC_Library.issue')),
                ('returned_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC_Library.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC_Library.student')),
            ],
        ),
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
    ]
