# Generated by Django 5.2.4 on 2026-07-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0006_contactform_message_student_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.CharField(null=True),
        ),
    ]
