# Generated by Django 6.0.3 on 2026-04-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0006_issue_return_delete_borrowrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='returned_book',
        ),
        migrations.RemoveField(
            model_name='return',
            name='student',
        ),
    ]
