# Generated by Django 6.0.3 on 2026-04-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0007_remove_return_returned_book_remove_return_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
