# Generated by Django 6.0.3 on 2026-08-13 05:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0007_book_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateField(default=datetime.datetime.today)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('issue_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AC_Library.issue')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AC_Library.student')),
            ],
        ),
    ]
