# Generated by Django 6.0.3 on 2026-04-22 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0008_alter_issue_issue_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='student',
            new_name='issue_student',
        ),
        migrations.AddField(
            model_name='return',
            name='return_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AC_Library.issue'),
        ),
        migrations.AlterField(
            model_name='return',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='AC_Library.issue'),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
