# Generated by Django 6.0.3 on 2026-08-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0008_remove_student_phone_number_alter_book_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='pickup_ready',
            field=models.BooleanField(default=False),
        ),
    ]
