# Generated by Django 6.0.3 on 2026-04-22 22:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0009_rename_student_issue_issue_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_genre',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issued_book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue_student',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='return',
            name='return_student',
        ),
        migrations.AddField(
            model_name='return',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AC_Library.student'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='overdue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='return',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AC_Library.issue'),
        ),
    ]
