# Generated by Django 6.0.3 on 2026-08-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AC_Library', '0009_issue_pickup_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='overdue_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
